### ISSUE TITLE
Database table does not exist error in Multisite if first Network Activated

### ISSUE THREAD

**Issue by knutsp** [front/cloud-blocks#13]
If this plugin is Network Activated only (not per site) the first time, the table "cloud_blocks" is not created when a site is accessed (and this plugin loaded).

> `WordPress database error Table 'mydbname.myprefix_3_cloud_blocks' doesn't exist for query SELECT * FROM nytt_3_cloud_blocks made by require('wp-blog-header.php')[,...,] WP_Hook->apply_filters, CloudBlocks\Blocks\Blocks->blocks_register_styles, CloudBlocks\Blocks\Options::get_all`

This because the custom table creation is only called at plugin activation. 

For a plugin, that creates persistent changes like this, to be network (Multisite) ready , it must check that it's installed upon loading (at least admin_init) by an option or directly checking existence of the resource (table). If not, run the installer on that site to create the tables.

Looping through sites at activation is not recommended as it dosn't take are of new sites added later.

I suggest `get_option( 'cloud_blocks_installed' )` or similar in this case.

**Comment by foadyousefi** [comment]
Thanks for the suggestion and reporting issue.

We already have a method for update database structure which checks for database table versions, if there was no match, it will create tables according to the provided schema, I just changed the action hook which was responsible for calling this method from `upgrader_process_complete` (which fires after plugin update) to `admin_init`. 

Now after network activating plugin, if you visit any sites admin, database table will be created automatically. 

Please try to update to latest version `1.1.3` and check if the issue fixed or not.

**Comment by foadyousefi** [comment]
Closing since there is no answer
