### ISSUE TITLE
Add modal with block info (like themes)

### ISSUE THREAD

**Issue by perandre** [front/cloud-blocks#2]
Just like the standard popup for themes, we can do the same for blocks. I realize that all info can actually come from package.json (except possible the description?):

![info](https://user-images.githubusercontent.com/118979/47358587-6a4d7880-d6ca-11e8-9c0b-1fcad742f185.jpg)

This is useful for promoting the author, and also get get a better view of the screenshot.

**Comment by perandre** [comment]
Perhaps @SofiaSousa has input on this as well.

**Comment by foadyousefi** [comment]
That was implemented and is available since version 1.0.5.

I will close this issue.
