### ISSUE TITLE
UI to upload zip file with custom block (outside cloud)

### ISSUE THREAD

**Issue by perandre** [front/cloud-blocks#3]
Since this is the block manager, it would be good to be able to upload zips for non Git people to use custom blocks outside of the cloud.

**Comment by foadyousefi** [comment]
Implemented in version 1.0.7

Its just like uploading plugin zip files as shown in the following screenshot. Simply choose your zip file and click on install button.


![cloud_blocks_ _upload_block_ui](https://user-images.githubusercontent.com/19663888/48414789-f09a2f00-e74b-11e8-90b5-7c1cb307e932.png)

**Comment by perandre** [comment]
Nice! I suggest a new line of text (smaller font): 

If using Git, we recommend adjusting your .gitignore and commit your block in /wp-content/uploads/gutenberg-blocks/*. [See documentation: Private blocks](https://github.com/front/cloud-blocks/blob/master/docs/private-blocks.md).

**Comment by foadyousefi** [comment]
The text is added.
