### ISSUE TITLE
Installed pane sometimes lists 0 blocks

### ISSUE THREAD

**Issue by perandre** [front/cloud-blocks#6]
See http://take.ms/PbxHM

Hitting refresh fixes it. I have only seen it happen when there are different WP flash message updates from other plugins at the top of the page. Not sure if related, tho.

**Comment by foadyousefi** [comment]
I'm not able to reproducing this issue.

Will test further but if the same happened again, can you please execute `window.store.state.installedBlocks` and `window.store.state.blocksCount` in your browsers devtool console and past the response here.

**Comment by foadyousefi** [comment]
@perandre 

I think this issue has been solved in recent releases. Can you please confirm and close this issue?
