### ISSUE TITLE
A few notes to version 1.1.0

### ISSUE THREAD

**Issue by ajotka** [front/cloud-blocks#7]
Hi! 
Thanks for "Local" tab in a new version. 

I noticed few things:

1. I build blocks automatically (CI) and blocks are still not installed in your panel.
2. I have a button "go to homepage" even if I don't have any link in package.json
3. There are always sample image even if I add a custom screenshot

![zrzut ekranu z 2019-01-03 22-22-14](https://user-images.githubusercontent.com/15144546/50662290-1f8f8d00-0fa6-11e9-907a-c3e96fb88094.png)

**Comment by foadyousefi** [comment]
Hi!

Thanks for reporting.

1. Before 1.1.0, all local blocks were installed automatically, also Wordpress had to scan `/wp-content/gutenberg-blocks` with every page load. This is not efficient. So in the last version (1.1.0), Its changed and only under admin > cloud blocks > Local, file system scan is done. But in order for blocks to work, they must be installed just like blocks from Gutenberg Cloud. This has another advantage. To disable a block, you don't need to delete it, just uninstall it and its enough.

2. Block authors must add their links to package.json. I think this is not that hard.

3. The issue with screenshots is that the filename must be `thumbnail`. The extension can be png, gif or jpg. I will change it back to screenshot with the next plugin update.

Sorry for that, we should update README.

**Comment by foadyousefi** [comment]
@ajotka Can you please update status and if everything is OK, close this issue?

**Comment by ajotka** [comment]
Yes, thank you for support. I checked and everything works.
