### ISSUE TITLE
Incorrect labels on buttons

### ISSUE THREAD

**Issue by ajotka** [front/cloud-blocks#9]
Hi!

I found two delete buttons.
I think, one of it should be Uninstall and it seems that you should check the translations after a string update.

![zrzut ekranu z 2019-01-08 11-09-46](https://user-images.githubusercontent.com/15144546/50824865-f4a39100-1337-11e9-86a4-564e18d9faa4.png)

**Comment by foadyousefi** [comment]
Thanks to reporting. 

Fixed it and since it is not a major bug, can wait for the next release.

**Comment by foadyousefi** [comment]
Closing!

**Comment by foadyousefi** [comment]
Closing this issue!
